# -*- coding: utf-8 mode: dockerfile -*- vim:sw=4:sts=4:et:ai:si:sta:fenc=utf-8
ARG REGISTRY=pubdocker.univ-reunion.fr
FROM $REGISTRY/src/base AS base
FROM $REGISTRY/src/postgres AS postgres

FROM dpage/pgadmin4:9

USER root
COPY --from=base /g/ /g/
COPY --from=postgres /g/ /g/
RUN /g/build.bb -z pgadmin && /g/pgadmin/fixperms

COPY config/initenv/ /g/initenv.d/

USER pgadmin
ENTRYPOINT ["/g/pgadmin/entrypoint"]
