# -*- coding: utf-8 mode: yaml -*- vim:sw=2:sts=2:et:ai:si:sta:fenc=utf-8

version: "3.7"

services:
  db:
    image: docker.devel.self/image/postgres:15-d12
    env_file: app.env
    environment: &db-environment
      APP_PROFILE: devel
      POSTGRES_PROFILE: devel
    volumes:
      - ./var/run:/run/postgresql
      - ./var/pgdata:/var/lib/postgresql/data
      - ./config/postgres/initdb:/docker-entrypoint-initdb.d
    ports:
      - 7432:5432
    deploy:
      update_config:
        order: stop-first

  cron-db:
    image: docker.devel.self/image/postgres:15-d12
    command: cron
    env_file: app.env
    environment:
      APP_DATADIR: /data/dre
      UPDATE_CRON_FILES: dl-dumps
      UPDATE_CRON_VARS: APP_DATADIR:POSTGRES_USER:POSTGRES_PASSWORD:DRE_URL:DRE_USER:DRE_PASS:DRE_PREFIX
      <<: *db-environment
    volumes:
      - ./var/run:/run/postgresql
      - ./var/dredata:/data/dre
      - ./config/cron:/cron-config
      - ./bin/dl-dumps:/usr/local/bin/dl-dumps
