#!/bin/bash
# -*- coding: utf-8 mode: sh -*- vim:sw=4:sts=4:et:ai:si:sta:fenc=utf-8
MYDIR="$(cd "$(dirname -- "$0")"; pwd)"
"$MYDIR/sbin/runphp" --bs --ue --ci || exit 1
DREMGR="$MYDIR"
source "$DREMGR/sbin/vendor/nulib/base/load.sh" || exit 1
source "$DREMGR/sbin/functions.sh" || exit 1

function all() {
    if [ -n "$MODE_SIMPLE" ]; then
        "$DREMGR/dbinst" ${Rebuild:+-b} "$@"
    else
        "$DREMGR/webfront" ${Rebuild:+-b} "$@" &&
        "$DREMGR/dbfront" "$@" &&
        "$DREMGR/dbinst" -A "$@"
    fi
}

action=start
Rebuild=
args=(
    "Gérer les frontaux et les instances de DRE configurées"
    #"usage"
    -s,--start action=start "Démarrer les services"
    -k,--stop action=stop "Arrêter les services"
    -r,--refresh action=refresh "(Re)démarrer les services si nécessaire"
    -R,--restart action=restart "Forcer le (re)démarrage des services"
    -b,-B,--rebuild Rebuild=1 "++Forcer le rebuild de l'image avant le démarrage"
)
parse_args "$@"; set -- "${args[@]}"

run_check_env || exit 0

setx Envfile=get_envfile
[ -f "$Envfile" ] || die "$(ppath "$Envfile"): fichier introuvable"
load_envs APP_PROFILES MODE_SIMPLE
[ -n "$APP_PROFILES" ] || die "Aucun profil n'est défini"

case "$action" in
start) all -s "$@";;
stop) all -k "$@";;
refresh) all -r "$@";;
restart) all -R "$@";;
*) die "$action: action non implémentée";;
esac
