#!/bin/bash
# -*- coding: utf-8 mode: sh -*- vim:sw=4:sts=4:et:ai:si:sta:fenc=utf-8
MYDIR="$(dirname -- "$0")"
"$MYDIR/sbin/bootstrap" && source "$MYDIR/sbin/vendor/nulib/php/load.sh" || exit 1
DREINST="$MYDIR"
source "$DREINST/sbin/functions.sh" || exit 1

function start_front() {
    local composefile="$DREINST/front-docker-compose.yml"
    [ -f "$composefile" ] || die "$composefile: fichier introuvable"
    if [ -n "$ForceStart" ]; then
        :
    elif dcrunning "$composefile"; then
        enote "Le frontal DRE est démarré"
        return
    fi

    #local reload
    #dcrunning "$composefile" && reload=1

    "$MYDIR/build" ${Rebuild:+--rebuild} || die
    estep "Démarrage du frontal DRE"
    docker compose -f "$composefile" up -d --wait || die

    #if [ -n "$reload" ]; then
    #    estep "Rechargement pgAdmin"
    #    sleep 2
    #    docker compose exec pgadmin /g/pgadmin/reload
    #fi
}

function stop_front() {
    local composefile="$DREINST/front-docker-compose.yml"
    [ -f "$composefile" ] || return 0
    if dcrunning "$composefile"; then
        estep "Arrêt du frontal DRE"
        docker compose -f "$composefile" down || die
    fi
}

function refresh_front() {
    local ForceStart=1
    start_front "$@"
}

function restart_front() {
    stop_front "$@"
    start_front "$@"
}

action=auto
Rebuild=
args=(
    "Gérer cette instance de DRE"
    #"usage"
    --check-only action=none "++Ne faire que la vérification de l'environnement"
    --bootstrap action=bootstrap "++Mettre à jour les outils en lançant de nouveau lib/sbin/bootstrap"
    -s,--start action=start "Démarrer le frontal DRE"
    -k,--stop action=stop "Arrêter le frontal DRE"
    -r,--refresh action=refresh "(Re)démarrer le frontal DRE si nécessaire"
    -R,--restart action=restart "Forcer le (re)démarrage du frontal DRE"
    -b,--rebuild Rebuild=1 "++Forcer le rebuild de l'image avant le démarrage"
)
parse_args "$@"; set -- "${args[@]}"

[ -f "$DREINST/front.env" ] || die "front.env: fichier introuvable"
eval "$(source "$DREINST/front.env"; echo_setv APP_PROFILES="$APP_PROFILES")"
[ -n "$APP_PROFILES" ] || die "Aucun profil n'est défini"

inst_check_env || exit 0
[ "$action" == auto ] && action=start
[ "$action" == none ] && exit 0

Profile=
ForceStart=
case "$action" in
bootstrap) "$DREINST/sbin/bootstrap" --force "$@";;
start) start_front "$@";;
stop) stop_front "$@";;
refresh) refresh_front "$@";;
restart) restart_front "$@";;
*) die "$action: action non implémentée";;
esac
