#!/bin/bash
# -*- coding: utf-8 mode: sh -*- vim:sw=4:sts=4:et:ai:si:sta:fenc=utf-8
MYDIR="$(dirname -- "$0")"
"$MYDIR/sbin/bootstrap" && source "$MYDIR/sbin/vendor/nulib/php/load.sh" || exit 1
DREINST="$MYDIR"
source "$DREINST/sbin/functions.sh" || exit 1

function start_dre() {
    local composefile="$DREINST/inst-docker-compose.yml"
    [ -f "$composefile" ] || die "$composefile: fichier introuvable"
    if [ -n "$ForceStart" ]; then
        :
    elif dcrunning "$composefile"; then
        enote "DRE [$Profile] est démarré"
        return
    fi

    "$MYDIR/build" ${Rebuild:+--rebuild} || die
    estep "Démarrage de DRE [$Profile]"
    docker compose -f "$composefile" up -d --wait || die
}

function stop_dre() {
    local composefile="$DREINST/inst-docker-compose.yml"
    [ -f "$composefile" ] || return 0
    if dcrunning "$composefile"; then
        estep "Arrêt de DRE [$Profile]"
        docker compose -f "$composefile" down || die
    fi
}

function refresh_dre() {
    local ForceStart=1
    start_dre "$@"
}

function restart_dre() {
    stop_dre "$@"
    start_dre "$@"
}

case "$MYNAME" in
*_start) Profile="${MYNAME%_start}";;
*) Profile=prod;;
esac
ForceUpdate=
action=auto
Rebuild=
args=(
    "Gérer cette instance de DRE"
    #"usage"
    --check-only action=none "++Ne faire que la vérification de l'environnement"
    --bootstrap action=bootstrap "++Mettre à jour les outils en lançant de nouveau lib/sbin/bootstrap"
    --force-update ForceUpdate=1 "++Forcer la mise à jour des fichiers dépendants"
    -g:,--profile Profile= "\
++Spécifier le profil. Un fichier de configuration PROFILE-profile.env doit exister.
Si cette option n'est pas spécifiée, le profil sélectionné par défaut est $Profile"
    -A,--all-profiles Profile=ALL "++Faire l'opération pour tous les profils définis dans all_profiles.env"
    -P,--prod Profile=prod "++alias pour --profile prod"
    -T,--test Profile=test "++alias pour --profile test"
    -s,--start action=start "Démarrer DRE"
    -k,--stop action=stop "Arrêter DRE"
    -r,--refresh action=refresh "(Re)démarrer DRE si nécessaire"
    -R,--restart action=restart "Forcer le (re)démarrage de DRE"
    --rebuild Rebuild=1 "++Forcer le rebuild de l'image"
)
parse_args "$@"; set -- "${args[@]}"

if [ "$Profile" == ALL ]; then
    [ -f "$DREINST/all_profiles.env" ] || die "all_profiles.env: fichier introuvable"
    eval "$(source "$DREINST/all_profiles.env"; echo_setv APP_PROFILES="$APP_PROFILES")"
    [ -n "$APP_PROFILES" ] || die "Aucun profil n'est défini"

    args=(
        ${ForceUpdate:+--force-update}
        ${Rebuild:+--rebuild}
    )
    case "$action" in
    none) args+=(--check-only);;
    bootstrap) args+=(--bootstrap);;
    auto) ;;
    *) args+=("--$action");;
    esac

    read -a profiles <<<"$APP_PROFILES"
    for profile in "${profiles[@]}"; do
        etitle "$profile" "$MYSELF" --profile "$profile" "${args[@]}"
    done
    exit
fi

Profile="${Profile##*/}"
Profile="${Profile%_profile.env}"
envfile="$DREINST/${Profile}_profile.env"

start_check_env || exit 0
if [ -f "$envfile" ]; then
    dredata="$MYDIR/var/${Profile}-dredata"
    for dir in addons downloads; do
        mkdir -p "$dredata/$dir"
    done
fi
[ "$action" == auto ] && action=start

[ -f "$envfile" ] || die "$Profile: profil invalide (${Profile}-profile.env: fichier de profil introuvable)"
[ "$action" == none ] && exit 0

ForceStart=
case "$action" in
bootstrap) "$DREINST/sbin/bootstrap" --force "$@";;
start) start_dre "$@";;
stop) stop_dre "$@";;
refresh) refresh_dre "$@";;
restart) restart_dre "$@";;
*) die "$action: action non implémentée";;
esac
