#!/bin/bash
# -*- coding: utf-8 mode: sh -*- vim:sw=4:sts=4:et:ai:si:sta:fenc=utf-8
MYDIR="$(cd "$(dirname -- "$0")"; pwd)"
"$MYDIR/sbin/runphp" --bs --ue --ci || exit 1
DREMGR="$MYDIR"
source "$DREMGR/sbin/vendor/nulib/base/load.sh" || exit 1
source "$DREMGR/sbin/functions.sh" || exit 1

function _set_composefiles() {
    composefile="$DREMGR/webfront-docker-compose.yml"
    composefiles=("$composefile")
    composeargs=(-f "$composefile")
    localfile="$DREMGR/webfront-docker-compose.local.yml"
    if [ -f "$localfile" ]; then
        composefiles+=("$localfile")
        composeargs+=(-f "$localfile")
    fi
}

function start_webfront() {
    local composefile localfile; local -a composefiles composeargs
    _set_composefiles

    [ -f "$composefile" ] || die "$composefile: fichier introuvable"
    if [ -n "$ForceStart" ]; then
        :
    elif dcrunning "${composefiles[@]}"; then
        enote "Le frontal web DREmgr est démarré"
        return
    fi

    #local reload
    #dcrunning "${composefiles[@]}" && reload=1

    "$MYDIR/build" ${Rebuild:+--rebuild} || die

    estep "Démarrage du frontal web DREmgr"
    docker compose "${composeargs[@]}" up -d --wait ${Recreate:+--force-recreate} || die

    #if [ -n "$reload" ]; then
    #    estep "Rechargement pgAdmin"
    #    sleep 2
    #    docker compose exec pgadmin /g/pgadmin/reload
    #fi
}

function stop_webfront() {
    local composefile localfile; local -a composefiles composeargs
    _set_composefiles

    [ -f "$composefile" ] || return 0
    if dcrunning "${composefiles[@]}"; then
        estep "Arrêt du frontal web DREmgr"
        docker compose "${composeargs[@]}" down || die
    fi
}

function refresh_webfront() {
    local ForceStart=1
    start_webfront "$@"
}

function restart_webfront() {
    local ForceStart=1
    local Recreate=1
    start_webfront "$@"
}

Profile=
ForceStart=
Recreate=
action=auto
Rebuild=
args=(
    "Gérer le frontal web de DREmgr"
    #"usage"
    --check-only action=none "++Ne faire que la vérification de l'environnement"
    -s,--start action=start "Démarrer le frontal web"
    -k,--stop action=stop "Arrêter le frontal web"
    -r,--refresh action=refresh "(Re)démarrer le frontal web si nécessaire"
    -R,--restart action=restart "Forcer le (re)démarrage du frontal web"
    -b,-B,--rebuild Rebuild=1 "++Forcer le rebuild de l'image avant le démarrage"
)
parse_args "$@"; set -- "${args[@]}"

IS_WEBFRONT=1
run_check_env || exit 0

setx Envfile=get_envfile
[ -f "$Envfile" ] || die "$(ppath "$Envfile"): fichier introuvable"
load_envs APP_PROFILES MODE_SIMPLE DATADIR
[ -n "$APP_PROFILES" ] || die "Aucun profil n'est défini"
[ -n "$MODE_SIMPLE" ] && ewarn "Le mode simple est activé. Le frontal web ne pourra pas fonctionner correctement"

[ "$action" == auto ] && action=start
[ "$action" == none ] && exit 0

ensure_dirs

case "$action" in
start) start_webfront "$@";;
stop) stop_webfront "$@";;
refresh) refresh_webfront "$@";;
restart) restart_webfront "$@";;
*) die "$action: action non implémentée";;
esac
