#!/bin/bash
# -*- coding: utf-8 mode: sh -*- vim:sw=4:sts=4:et:ai:si:sta:fenc=utf-8
MYDIR="$(cd "$(dirname -- "$0")"; pwd)"
"$MYDIR/sbin/rundk" --bs --ue --ci || exit 1
DREMGR="$MYDIR"
source "$DREMGR/sbin/vendor/nulib/php/load.sh" || exit 1
source "$DREMGR/sbin/functions.sh" || exit 1

function start_webfront() {
    local composefile="$DREMGR/webfront-docker-compose.yml"
    [ -f "$composefile" ] || die "$composefile: fichier introuvable"
    if [ -n "$ForceStart" ]; then
        :
    elif dcrunning "$composefile"; then
        enote "Le frontal web DRE est démarré"
        return
    fi

    #local reload
    #dcrunning "$composefile" && reload=1

    "$MYDIR/build" ${Rebuild:+--rebuild} || die

    estep "Démarrage du frontal web DRE"
    docker compose -f "$composefile" up -d --wait || die

    #if [ -n "$reload" ]; then
    #    estep "Rechargement pgAdmin"
    #    sleep 2
    #    docker compose exec pgadmin /g/pgadmin/reload
    #fi
}

function stop_webfront() {
    local composefile="$DREMGR/webfront-docker-compose.yml"
    [ -f "$composefile" ] || return 0
    if dcrunning "$composefile"; then
        estep "Arrêt du frontal web DRE"
        docker compose -f "$composefile" down || die
    fi
}

function refresh_webfront() {
    local ForceStart=1
    start_webfront "$@"
}

function restart_webfront() {
    stop_webfront "$@"
    start_webfront "$@"
}

action=auto
Rebuild=
args=(
    "Gérer cette instance de DRE"
    #"usage"
    --check-only action=none "++Ne faire que la vérification de l'environnement"
    -s,--start action=start "Démarrer le frontal web DRE"
    -k,--stop action=stop "Arrêter le frontal web DRE"
    -r,--refresh action=refresh "(Re)démarrer le frontal web DRE si nécessaire"
    -R,--restart action=restart "Forcer le (re)démarrage du frontal web DRE"
    -b,--rebuild Rebuild=1 "++Forcer le rebuild de l'image avant le démarrage"
)
parse_args "$@"; set -- "${args[@]}"

[ -f "$DREMGR/dremgr.env" ] || die "dremgr.env: fichier introuvable"
eval "$(source "$DREMGR/dremgr.env"; echo_setv APP_PROFILES="$APP_PROFILES")"
[ -n "$APP_PROFILES" ] || die "Aucun profil n'est défini"

IS_WEBFRONT=1
run_check_env || exit 0
[ "$action" == auto ] && action=start
[ "$action" == none ] && exit 0

Profile=
ForceStart=
case "$action" in
start) start_webfront "$@";;
stop) stop_webfront "$@";;
refresh) refresh_webfront "$@";;
restart) restart_webfront "$@";;
*) die "$action: action non implémentée";;
esac
