#!/bin/bash
# -*- coding: utf-8 mode: sh -*- vim:sw=4:sts=4:et:ai:si:sta:fenc=utf-8
source /etc/nulib.sh || exit 1

args=(-c "$MYDIR/dremgr.yml")
[ "$MYNAME" != dump ] && args+=("${MYNAME%_dump}_dre")
db.dump.php "${args[@]}" "$@"
