#!/bin/bash
# -*- coding: utf-8 mode: sh -*- vim:sw=4:sts=4:et:ai:si:sta:fenc=utf-8
source /etc/nulib.sh || exit 1

ADM="host=pegase-dre.self port=5432 dbname=pgbouncer user=pgbouncer password=admin"
RW="host=pegase-dre.self port=5432 dbname=dre user=root password=admin"
RO="host=pegase-dre.self port=5432 dbname=dre user=reader password=reader"

conn="$RW"
inputs=()
args=(
    "lancer une console psql sur l'instance de dev"
    -w,--write conn="$RW" "accès en écriture. c'est l'option par défaut"
    -r,--read conn="$RO" "accès en lecture seule"
    -a,--admin conn="$ADM" "accès à pgbouncer"
    -f:,--input:INPUT inputs
)
parse_args "$@"; set -- "${args[@]}"

if [ ${#inputs[*]} -gt 0 ]; then
    for input in "${inputs[@]}"; do
        psql -d "$conn" "$@" -f "$input"
    done
else
    exec psql -d "$conn" "$@"
fi
